#######################
# Theme Customization #
#######################

title: Star' s note                             # used in <title> tag & site header
author: Star Du                        # used in a <meta> tag & /feed.xml
description: ">A guy interested in too many things."
slogan:                            # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: https://star-du.github.io/           # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
    #   - name: Projects
    #     url: /projects
    #     icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/star-du/star-du.github.io
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: About
    url: /about
    icon: /i/icons.svg#posts 
    #   - name: Contact
    #     scheme: mailto      # these keys enable email obfuscation.
    #     handle: hello       # you know, to protect you from bots. (handle and domain
    #     domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    #     icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: HUSTAU 小程序
    teaser: 用于管理物资和场地，使用了“云开发”
    url: https://github.com/star-du/cloud-mini-app
    role: Core Team
    category: Dev

#################
# Site Settings #
#################

incremental: false # turn off to avoid unexpected behaviors
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:title

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
